blank_issues_enabled: false
contact_links:
  - name: Suggest a resource
    url: https://github.com/chentsulin/awesome-graphql/blob/HEAD/CONTRIBUTING.md
    about: Read the contribution guidelines and submit one resource per pull request.
